# Stage 7 Configuration - Generated by setup
# This file contains the configuration from the stage7_config_script artifact
source "$(dirname "${BASH_SOURCE[0]}")/../config_reference.sh" 2>/dev/null || {
    echo "Configuration reference not found. Using defaults."
    export STAGE7_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    export PYTHON_ENV="$STAGE7_HOME/../venv"
    export DATA_DIR="$STAGE7_HOME/data"
    export LOGS_DIR="$STAGE7_HOME/logs"
    export REALTIME_DIR="$STAGE7_HOME/data/realtime"
    export KEY_MINUTES="59 60 69 70 79 80"
    export ML_WEIGHT=0.7
    export HISTORICAL_WEIGHT=0.3
}
