version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sofascore_postgres_fixed
    environment:
      POSTGRES_DB: sofascore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_fixed:/var/lib/postgresql/data
    networks:
      - sofascore_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sofascore_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_fixed:
    driver: local

networks:
  sofascore_network:
    driver: bridge
